### ISSUE TITLE
Thanks and a little help !!

### ISSUE THREAD

**Issue by complete-dope** [AndreyGermanov/yolov8_onnx_javascript#1]
Thanks for the rescue man !! 

Could you help in detecting the yolov8-pose estimator onnx javascript !! that would really help !!

**Comment by AndreyGermanov** [comment]
It's out of scope here, but perhaps will create a separate repository for YOLOv8 pose estimation when have time.
Follow me to know when it happens.

**Comment by complete-dope** [comment]
Thanks for this wonderful repo and blog post
No worries I did it
